pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=pull_request
    actions:
      merge:
        method: squash
      label:
        add: [dependency-update]
