version: '3'
services:
  db:
    image: mongo:4.2.3
    ports:
      - 27017:27017
    volumes:
    - ./scripts/databases/mongo.js:/docker-entrypoint-initdb.d/database.js:ro
  redis:
    image: redis:5.0.7
    ports:
    - 6379:6379
  nginx:
    image: nginx:stable-alpine
    volumes:
    - ./scripts/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    - ./scripts/nginx/cert.key:/etc/nginx/ssl/cert.key
    - ./scripts/nginx/cert.pem:/etc/nginx/ssl/cert.pem
    network_mode: "host"
  jaeger:
    image: jaegertracing/all-in-one:1.17
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 14268:14268
    - 9411:9411
  rabbitmq:
    image: rabbitmq:3.8.2-management
    hostname: "rabbitmq"
    ports:
    - 5672:5672
    - 15672:15672
  minio:
    image: minio/minio
    ports:
      - 9999:9000/udp
    environment:
      - MINIO_ACCESS_KEY=minio_admin
      - MINIO_SECRET_KEY=minio_adminpw
