ARG COMPOSE_PROJECT_NAME
FROM imazsak-build:${COMPOSE_PROJECT_NAME} as builder

FROM openjdk:8-alpine
USER root
RUN apk add --no-cache bash && \
    adduser -S -u 1001 imazsak
USER 1001
EXPOSE 9000
ENTRYPOINT ["/app/bin/imazsak"]
CMD []
COPY --from=builder --chown=1001:root /app/target/universal/stage /app
