version: '3'
services:
  db:
    image: mongo:4.2.8
    volumes:
    - ./scripts/databases/mongo.js:/docker-entrypoint-initdb.d/database.js:ro
  redis:
    image: redis:5.0.12
  imazsak:
    build:
      context: .
      dockerfile: Dockerfile-test
    image: imazsak-build:${COMPOSE_PROJECT_NAME}
    command: sleep 9999
    depends_on:
      - db
      - redis
    environment:
      - DB_URI=mongodb://db/imazsak
      - REDIS_HOST=redis
