FROM hseeberger/scala-sbt:8u222_1.3.5_2.13.1
COPY build.sbt /app/build.sbt
COPY project /app/project
WORKDIR /app
RUN sbt update test:update it:update
COPY . .
RUN sbt compile test:compile it:compile stage
